<?php 
return array (
  'status' => 'int',
  'number' => 'int',
  'title' => 'string',
  'tag' => 'string',
  'difficulty' => 'int',
  'rate' => 'string',
  'submitTime' => 'int',
  'ACTime' => 'int',
  'content' => 'string',
  'inputFormat' => 'string',
  'outputFormat' => 'string',
  'sampleInput' => 'string',
  'sampleOutput' => 'string',
  'hint' => 'string',
  'provider' => 'string',
  'timeLimit' => 'float',
  'memoryLimit' => 'int',
  '_pk' => 'number',
  '_autoinc' => 'number',
);